theme: jekyll-theme-cayman
title: Tutorial on Designing Benchmarks for Measuring Automatic Algorithm Performance on Research Data
description: On October 29th at the 14th IEEE International Conference on eScience 2018, Amsterdam, the Netherlands
